### ISSUE TITLE
Empty URL in Trending Service Causes Application Crash

### ISSUE THREAD

**Issue by Shimeming** [taipei-doit/TownPass#1]
In the TrendingServiceModel class located at `lib/page/city_service/model/trending_service_model.dart`, the url field for the "施工資訊" service is assigned an empty string (`url: ''`). This becomes problematic when the application tries to navigate to this service.

In the file `lib/util/tp_web_view.dart:69`, the `loadUrl` method is called to load a URL.
If we try to navigate "施工資訊", the app will crash and the following error will occur:

> [!CAUTION]
> Exception has occurred.
> _AssertionError ('package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart': Failed assertion: line
 1788 pos 12: 'urlRequest.url != null && urlRequest.url.toString().isNotEmpty': is not true.)

**Comment by TmTsimp** [comment]
Webview now handles the assertion and shows the error url. (v0.0.11)

**Comment by TmTsimp** [comment]
Webview now handles the assertion and shows the error url. (v0.0.11)
